### ISSUE TITLE
Question: How to use the action with workflow_run

### ISSUE THREAD

**Issue by dgokcin** [pascalgn/automerge-action#188]
Hello I have an auto pr action which creates a PR to the develop branch whenever a hotfix is merged to the master branch. I want to merge the auto pr to the develop branch with this action but I am hitting some limitations. The develop branch is a protected branch which needs at least 1 approvers and which expects some checks to pass. I also have created a dedicated bot user and a PAT. I want to merge the auto prs(which have a pr number output) into the develop branch without waiting for approvers. How can I solve this problem? Thanks!

**Comment by pascalgn** [comment]
I think this isn't really possible, due to the way GH protected branches work: when you have protections (e.g. 1 approval), this counts for all PRs, no matter how they're created. The only possible solution I see is to add the user of the PAT to the list of administrators for that repository and then uncheck "Include administrators" in the branch protection rules.

**Comment by dgokcin** [comment]
I worked around my issue by adding an auto approve step. my flow is: auto pr is created with github app token -> github-actions-bot approves the pr -> github app merges the pr.

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
