### ISSUE TITLE
Confusion around priority of automerge and autorebase

### ISSUE THREAD

**Issue by phillbaker** [pascalgn/automerge-action#20]
Thanks for  your hard work on this! Had a question / bit of confusion that I'd like to clarify.

The Readme says:

> `automerge` means that changes from the base branch will automatically be merged into the pull request, but only when "Require branches to be up to date before merging" is enabled in the branch protection rules. When the PR is ready, it will automatically be merged.
> `autorebase` means that when changes happen in the base branch, the pull request will be rebased onto the base branch. When the PR is ready, it will automatically be merged into the base branch.

Looking at the code, here: https://github.com/pascalgn/automerge-action/blob/39c078f5a668a597dbfc3dbaf307ce22befac4ae/lib/update.js#L45-L48

if both `autorebase` and `automerge` labels are applied to a PR, the merge functionality takes precedence, which was a bit surprising.

What do you think of these potential approaches?
* If both labels are applied, throw an error as an undetermined state. Add a note in the readme.
* Define UPDATE_METHOD_REBASE and UPDATE_METHOD_MERGE which separates the squash/merge/rebase action of the automerge vs. autorebase
* (breaking change) Limit the automerge functionality to just merging a PR, if a PR meets the criteria. Define a separate "autoupdate" functionality that would either do merges from the base branch or rebase.

**Comment by pascalgn** [comment]
Regarding the first point: Yes, you're absolutely right, that is confusing and we should change it by throwing an error, as you suggested.

About the other two points: I think it makes sense to have it like you suggested, but it would increase the complexity of this action too much for my liking. So I'm now thinking about splitting the functionality into two actions, automerge-action basically stays the same except the updating logic is removed and a new action autoupdate-action to automatically update PRs. This also makes sense because the update action only needs to run when the base branch has been pushed to (so different triggers)

**Comment by pascalgn** [comment]
Please also see my reply in #16!

**Comment by pascalgn** [comment]
This should be fixed with #27 and the addition of `MERGE_METHOD`, which clearly indicates which action will be used. If you have any other questions, please let me know!
