### ISSUE TITLE
Does it check on PR build failure?

### ISSUE THREAD

**Issue by chenrui333** [pascalgn/automerge-action#23]
I wonder if this action does check on the PR build failure before doing the auto-merge. Thanks!

**Comment by chenrui333** [comment]
```
INFO Event name: pull_request
INFO Updating PR #1883 Update automerge action
INFO No update necessary
INFO PR is probably ready: mergeable_state: unknown
INFO PR successfully merged!
```

Looks like it does not check the PR build status before the merge.

**Comment by chenrui333** [comment]
Right now i have a travis PR build though.

![image](https://user-images.githubusercontent.com/1580956/67892754-c5127f00-fb2b-11e9-9492-35e45d1bbeeb.png)

**Comment by pascalgn** [comment]
Yes, I'm really sorry about this and if you look into the git history of this action, the behaviour was different in earlier versions. The problem lies in this line:

```
INFO PR is probably ready: mergeable_state: unknown
```

The GitHub API isn't too great, unfortunately. There is another issue in this repository (#8) where GitHub triggers the check_run event (after e.g. Jenkins has completed the checks), but when trying to merge, the merge fails with "Required status check is expected." So GitHub reports the wrong PR state and there's not much I can do, unfortunately.

In your case, I think it can help to mark the "Travis CI" check as a "Required status check" under repository settings ("Branch protection"), so that the PR really can only be merged once the check has finished successfully.

I'm sorry that I can't give you a better solution!

**Comment by chenrui333** [comment]
No worries, thanks though!
