### ISSUE TITLE
Provide output indicating if merge happened

### ISSUE THREAD

**Issue by Cyberbeni** [pascalgn/automerge-action#36]
It would be useful if you want to send a push notification on successful merges.

**Comment by pascalgn** [comment]
In merge.js there's the line `logger.info("PR successfully merged!");`, maybe that helps?

**Comment by Cyberbeni** [comment]
Can you use the log for other actions?

I meant the @actions/core.setOutput function: https://github.com/actions/cache/blob/3d01b4eb53c7cbc3df0c28cb47cc45754127fe57/src/utils/actionUtils.ts#L58

**Comment by pascalgn** [comment]
Ah, I didn't know that existed. Yes, sounds like a good idea.

I had a look at the documentation and found https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#outputs

So the action should define some output ID. Do you have any opinions on how the output should look like? I can think of `result: merged` and `merged: true` from the top of my head. I'm not sure what makes more sense for other actions to consume

**Comment by Cyberbeni** [comment]
People could be using checks that just reports on the pull request and doesn't run in their workflows, like code quality checking, so having a `result` with `merged`/`merge_blocked`/`other` values would probably be the best in my opinion.

**Comment by pascalgn** [comment]
I think it's a bit more complicated, because the action has different result types, based on the event that triggered it:

- push: not sure if anyone is really using it, but in theory this will affect multiple branches/PRs
- status: GH reports status results per commit, so this action can affect multiple branches/PRs
- pull_request, pull_request_review: these events are triggered per PR, so will only affect a single branch/PR

The output name needs to be fixed and as far as I can tell, GH only supports strings, no complex objects, as outputs. But in the case of multiple affected PRs, we would need something like `{ "PR#123": "merged", "PR#456": "merge_blocked" }`

**Comment by pascalgn** [comment]
I think this is useful, but I don't need this at the moment and I don't see myself implementing this anytime soon. However, feel very free to work on this and if you create a PR for it, I will have a look at it in a timely manner!

I will close this issue for now. If you have any new information or need any help, feel free to reopen it!

**Comment by ZacSweers** [comment]
what about something via env?

`echo "::set-env name=MERGE_SUCCESS::true"`

Then downstream steps could check that?
