### ISSUE TITLE
Automatic removal of `automerge` labels upon successful merge

### ISSUE THREAD

**Issue by regexident** [pascalgn/automerge-action#49]
Currently the `automerge` labels are used for triggering the action, and then left as is.

It would be nice if **automerge-action** had a way to automatically remove `automerge` labels upon successful merge (even better: do so by default!), so that the `automerge` labels

- **do not clutter the issues list after use,**

but instead

- **allow for filtering for PR that are currently queued for automerging**.

**Comment by pascalgn** [comment]
Yes, I think it's a good idea! However, the way this action is configured, it's not immediately clear which labels should be removed. The default is `MERGE_LABELS: "automerge"`, but it could also be configured like `MERGE_LABELS: "!wip,size/XS"` where it wouldn't make sense to remove the size label after merging.

I would suggest to add a new option, possibly `MERGE_REMOVE_LABELS`, which takes a list of labels that will be removed after merging the PR. I think the default could be `MERGE_REMOVE_LABELS: "automerge"`, because I agree that it doesn't make much sense to keep the label after merging.

This is a nice feature, but I don't consider it very important. I might take a look at it at some time, but I cannot promise anything. If you want to provide a PR for it, feel very free, I will be happy to have a look! 👍

**Comment by karfau** [comment]
I actually like to see what PR's in the list of closed PRs have been automatically merged.
Although this action is not expected to make use of the label afterwards, I would consider this a breaking change. (People could rely on the label staying in place.)

In case you want to stick to removing the label by default, please consider to only remove it by default if the label is also present in `MERGE_LABELS`...

**Comment by regexident** [comment]
You are absolutely right, @karfau! Removal should be strictly opt-in.

I have thus changed the default value for `MERGE_REMOVE_LABELS` from `"automerge"` to `""`.

Thanks for your input!

**Comment by pascalgn** [comment]
Closed with #50
