### ISSUE TITLE
Multiple outstanding "ready" PR contend with each other

### ISSUE THREAD

**Issue by benoy-sifive** [pascalgn/automerge-action#73]
For a repo that has several folks contributing, there are situations where multiple outstanding pull requests (PRs) can become "ready" (pass checks, has required approvals, is up-to-date).  Then, all ready PRs contend with each other as they try to update and rerun checks causing unnecessary reruns of Action checks.  This problem is exaggerated  when the checks are a significant number of minutes.

A potential solution would be if only the oldest PR was allowed to proceed while the other wait for a trigger of push to master from that oldest PR and then the new oldest PR is allowed to proceed.  Does a feature like this already exist?

**Comment by pascalgn** [comment]
Such a feature does not yet exist, but it was already requested by another user some time ago in #13.

Nothing much has changed since then, so the status is still the same: I think it's a useful feature, but I don't need it, so it's unlikely that I will implement it. However, if you want to give it a go, feel very free and I will have a look at the PR! 👍

**Comment by benoy-sifive** [comment]
Thanks for replying!  If I get some time, I may take a stab at it.  For now, I'll close this issue since it is a duplicate.

**Comment by jbcpollak** [comment]
didn't want to open a new ticket, but we are happily using automerge and I was wondering if its compatible with GitHub's newish merge-queue? Can automerge enqueue the merge instead of actually doing it?

unrelated, but we continue to use automerge specifically because don't want devs writing their own commit messages, we have those checked and linted as part of the PR process and want to ensure they stay correct on merge.
