### ISSUE TITLE
Caching Docker steps

### ISSUE THREAD

**Issue by gilbertl** [pascalgn/automerge-action#77]
Github recently lowered the number of free Github action minutes and we're noticing a much higher bill even though the only Github action we use on the team is automerge.

I took a quick look and saw that every automerge workflow takes roughly 20-40s for us. At a team of 4 people, it adds up quickly.

The bulk of the automerge action seems to be on the Docker build step:

`(4/8) Installing libcurl (7.64.0-r3)
(5/8) Installing expat (2.2.8-r0)
(6/8) Installing pcre2 (10.32-r1)
(7/8) Installing git (2.20.4-r0)
(8/8) Installing openssl (1.1.1g-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20191127-r0.trigger
OK: 22 MiB in 24 packages
Removing intermediate container ee731bba2734
 ---> 6ba513d94c77
Step 7/9 : COPY . /tmp/src/
 ---> 9d1cf0377b17
Step 8/9 : RUN yarn global add "file:/tmp/src" && rm -rf /tmp/src
 ---> Running in 426fd5d88b34
yarn global v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "automerge-action@0.0.1" with binaries:
      - automerge-action
Done in 1.33s.
Removing intermediate container 426fd5d88b34
 ---> dbb47f2b2ab6
Step 9/9 : ENTRYPOINT [ "automerge-action" ]
 ---> Running in 374c7d9b15ce
Removing intermediate container 374c7d9b15ce
 ---> 3a35d505ab7e
Successfully built 3a35d505ab7e
Successfully tagged be76db:27223492625140b087343075d88d849b`

The logs here took 23s for example. 

I am not a Docker expert, but I think one feature of Docker is that each step can be cached. 

A quick search showed that there's some actions out there that might allow that:

https://github.community/t5/GitHub-Actions/Cache-a-Docker-image-built-in-workflow/td-p/31805
https://github.com/marketplace/actions/build-docker-images-using-cache

Have we tried this already ?

**Comment by AnandChowdhary** [comment]
Relevant discussion: #24

**Comment by yarinm** [comment]
Do we have to use docker to run this? Why not make this action run as nodejs ? 
See this [example](https://github.com/jwalton/gh-find-current-pr/blob/master/action.yml#L20).

I'm on a large team with many events that trigger this action and it's starting to cost us a lot (it's about 10K actions per day) which is absurd. I think changing this to a nodejs action will improve it.

**Comment by pascalgn** [comment]
Yes, changing this action to use nodejs directly would be a viable option, I think. The release process will be a bit more complicated, though, since the npm dependencies need to be added. But I will have a look into this!

However, at about 10k action invocations per day, I suggest you maybe consider changing this to use "schedule" events instead: even if you set it to run once every minute, it will "only" be around 1500 invocations per day.

**Comment by yarinm** [comment]
What I'm experiencing is a large amount of "status" events which is unclear what is their origin it seems that be duplicating x6-7 times (per developer) I'm not sure why is that. I suspect that because we have a CircleCI  flows that build around 30 components per commit (we have a monorepo) that might cause the issue, though I don't see 30x status events per commit.

@pascalgn By changing the action to be scheduled will it run on all open PRs with the labels?

**Comment by pascalgn** [comment]
The action is now a JS action and no longer uses Docker now (see #125 and #135) so I will close this 😊
